source 'https://rubygems.org'

gem 'rails',                   '3.2.12'
gem 'sqlite3'
gem 'jquery-rails',            '2.0.2'
gem 'twitter-bootstrap-rails', '2.1.0'
gem 'will_paginate',           '3.0.3'
gem 'showbuilder',             '0.0.15'

group :assets do
  gem 'sass-rails',   '3.2.3'
  gem 'coffee-rails', '3.2.1'
  gem 'uglifier',     '1.0.3'
  gem 'therubyracer', '0.10.2'
end

group :development, :test do
  gem 'pry',                '0.9.12'
  gem 'pry-nav',            '0.2.2'
  gem 'pry-stack_explorer', '0.4.9'
  gem 'pry-rails',          '0.2.2'
end

group :development do
  gem 'better_errors',     '0.6.0'
  gem 'binding_of_caller', '0.7.1'
end

group :test do
  gem 'turn',           '0.9.6', :require => false
  gem 'spork',          '1.0.0rc3'
  gem 'spork-testunit', '0.0.8'
end
